### ISSUE TITLE
Create template milestone

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#10]
create a template milestone containing template user stories, for a typical ACM event.
example:
milestone
- make flyer
- book space
- book ACM calendar date
- send flyer to sarah
- updating our docs about contacts, etc
- steps taken from the event workflows

**Comment by Wmaxlees** [comment]
This looks like it's been finished

https://docs.google.com/document/d/1G0-yQAmGyF9yAFsbDiJcGXWne4jqH3ERJIuGLTylodM/edit

I think it will fill in more as we start actually planning events but, for now, I think we can call this user story done.

**Comment by robfitzgerald** [comment]
i agree
