### ISSUE TITLE
Digitize workflows 

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#11]
so as cool as these pictures are, they're challenging to read if you're not Robert Fitzgerald.  so, use a drawing program and redo them.

these were to represent the workflows for intake (labelled Jason) and for event operation management (labelled Next Guy).

![img_20150804_001927 2](https://cloud.githubusercontent.com/assets/7003022/9054503/774e6dd0-3a3f-11e5-97f4-c7846640b548.jpg)

![img_20150804_001937 2](https://cloud.githubusercontent.com/assets/7003022/9054461/f25ba656-3a3e-11e5-83cc-dcde970128c2.jpg)

**Comment by Wmaxlees** [comment]
https://www.draw.io/

**Comment by Wmaxlees** [comment]
https://www.gliffy.com/
