### ISSUE TITLE
Engagement Letter

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#12]
Write final draft of engagement letter

**Comment by Wmaxlees** [comment]
@robfitzgerald Has there been any word from Dat? If we aren't going to have a company portal up, I will need to make some small changes to the engagement letter.

**Comment by robfitzgerald** [comment]
based on where we are at with the site it looks to me like making that change is the safer bet.

**Comment by Wmaxlees** [comment]
Have you seen the most recent version? If we just fill out https://docs.google.com/document/d/1MhEZlV4QlE6Dfie0sGCRYIGZ8B5WbhQpUFNWWzgdTKo and load it into the database, I think at least that portion of the site will be working. I'm not sure how I feel about that yet

**Comment by robfitzgerald** [comment]
ya that doesn't seem like an improvement over a few bullet points in the letter.

**Comment by Wmaxlees** [comment]
That's true. Okay, we'll skip the site for now then

**Comment by robfitzgerald** [comment]
here's my edit:  https://docs.google.com/document/d/11rEyAJPZJZgatThHypZp52pk5cUdKiDp-MtiSO2RbTk/edit

**Comment by robfitzgerald** [comment]
i've got a little concern about the biz process flow here for sending out letters.  shouldn't we send the first letter from a ucdenver.edu email address, so it's seen by the recipient as an actual student in their mailbox, not a gmail account?

if we agree, and jason's handling this, then i'm thinking emails should be sent from jason's email, and a reply-to should be set for ucd.acm@gmail.com in the email.  and, if it's coming from jason, then the signature line could just be him:

> Jason Minor
> Secretary, Association for Computing Machinery
> UC Denver Chapter

**Comment by robfitzgerald** [comment]
@minor-jason ^^

**Comment by Wmaxlees** [comment]
Good idea. Should we create a new user story about trying to get a `acm@ucdenver.edu` email address.

**Comment by robfitzgerald** [comment]
Probably a conversation with student life

**Comment by Wmaxlees** [comment]
Would we actually use that email if we had it, though?

**Comment by robfitzgerald** [comment]
In place of the Google one? I dunno, you may have a point there

**Comment by robfitzgerald** [comment]
I mean, we always need a bucket email address to catch all general inquiries. If we are happy with the Google one (which also serves as our document storage and calendar integration) then make that's fine
