### ISSUE TITLE
Event accepted template

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#15]
A template for "your event is accepted and here's your new contact for the details" notification for handing off from intake to a specific operational lead needs to be written

**Comment by robfitzgerald** [comment]
[max] Should we mention the invitation to tech expo here?
[rob] i’d say no.  let’s keep it simple.  consider the situation of a first-time event with a new company.  we can get a feel for them at the event, to decide if we want to mention it.  for example, in the case of idTech, they might take us up on a tech expo invite, and we would be like, oh, crap, they’re not from the DEN area.

**Comment by robfitzgerald** [comment]
another vote on this: most have already received the plug on the expo from the engagement letter (which, by the way, looks awesome).

**Comment by robfitzgerald** [comment]
perhaps there should be a post-event email.  that gives us a chance to get feedback from the company (opportunity to leverage google forms here).  in that email, we could mention the tech expo.

**Comment by Wmaxlees** [comment]
I like the post-event email that involves a reminder of the tech expo and a chance to get feedback. I'm going to make a new user story for it.
