### ISSUE TITLE
Company Registry Template

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#18]
create a spreadsheet template that will contain a registry for a company.  a registry will include the following (using mashup made up jsonish wonkypseudocode notation):

company name
contact name
contact role
contact email
contact phone
contact history = [
date | initiator (us/them) | their contact | reason contacted | response | notes
]

Q: i'm not sure if events = [] should live in here since it will be proudly showcased on the website.  DRY.  we could leverage that and make it where we store business data about events as well.

eventually, room to expand to hold other data such as 'wants interns?' or other notes.  er, i guess, that's what 'notes' is for

**Comment by robfitzgerald** [comment]
company name will be in the filename.  removing it from the list.

**Comment by Wmaxlees** [comment]
Hmmmmm. Interesting question. My immediate reaction: It would be an inconvenience, and could possible cause problems, to have duplicate data in two areas that both need to be updated when things change. All of our other similar data will live inside Google Docs, though. It might be a pain to have to switch back and forth. 

But there may be some way of generating reports. Or some other awesome way of integrating the two. Or we could transfer a lot of our data over to the website (that may be a lot of work, though)

I don't know. I need to let it process a bit probably.

**Comment by Wmaxlees** [comment]
The template looks good. I might add a general notes section, though.

**Comment by robfitzgerald** [comment]
done

**Comment by Wmaxlees** [comment]
I approve. Should we make a new issue about figuring out this:

Q: i'm not sure if events = [] should live in here since it will be proudly showcased on the website. DRY. we could leverage that and make it where we store business data about events as well.

and closing this user story?

**Comment by robfitzgerald** [comment]
that will likely just come up if it's a bad design we'll just be like "we need to store events here too"

**Comment by robfitzgerald** [comment]
@Wmaxlees, feel free to make the user story if you want, but, i don't think we need it.
