### ISSUE TITLE
Digitize Intake Workflow

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#21]
![img_20150804_001927 2](https://cloud.githubusercontent.com/assets/7003022/9054503/774e6dd0-3a3f-11e5-97f4-c7846640b548.jpg)

**Comment by Wmaxlees** [comment]
I think the current version (v7) is pretty solid. I'm guessing this will mostly end up acting like a guideline rather than something to be strictly adhered to? I'm going to move it over to Google Docs

**Comment by robfitzgerald** [comment]
sounds good to me

**Comment by robfitzgerald** [comment]
guideline, def

**Comment by Wmaxlees** [comment]
Actually, since this is mostly going to be Jason, I think we should get his approval as well before closing this

**Comment by robfitzgerald** [comment]
sure.  i just sent him an email about setting up zenhub.

**Comment by minor-jason** [comment]
I got yer ZenHub right here

**Comment by robfitzgerald** [comment]
blammmmmmm

**Comment by robfitzgerald** [comment]
ya @minor-jason refer to this: https://www.gliffy.com/go/html5/8655929

**Comment by robfitzgerald** [comment]
if you approve, then slide this user story on down to the closed pipeline.

**Comment by minor-jason** [comment]
I think this looks great. This will be something real nice to leave for our successors.
