### ISSUE TITLE
Orgsync - Trivia Night email / Treasurer position

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#26]
make an orgsync announcement that gives trivia night details, and mention a vote for Treasurer.

**Comment by robfitzgerald** [comment]
Dear ACM Members,

As you may or may not have noticed, school is back in session.  This sometimes take a week to set in.  That is why ACM will be holding a Trivia Night event one week from today in the Lawrence Street Student Lounge.

We will play trivia, with pizza, and with prizes for the winning team.  We will also be holding a vote for a treasurer officer vacancy.

Please stop by.  We look forward to seeing you and catching up.

Sincerely,

Rob, Max, and Jason
ACM of UC Denver

![Uploading Trivia Bill Single fall 2015.png…]()

**Comment by Wmaxlees** [comment]
I like it

**Comment by robfitzgerald** [comment]
k i'm going for it
