### ISSUE TITLE
find time for officer meetings

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#28]
hey wats a good time for officer meetings?
what's a good regularity?

I was noticing we could all meet before our 930am MW class.
I also have time free after 12:30p on MW, and after 3:30pm on TuTh

**Comment by Wmaxlees** [comment]
I can meet on either of those times you said on MW. I would prefer the 12:30pm meeting time, though. TuTh, won't work for me. I think weekly is good if we can.

**Comment by robfitzgerald** [comment]
Aye, Tue Thu also bad for me

**Comment by minor-jason** [comment]
Those MW times are good for me

**Comment by robfitzgerald** [comment]
OK. I would suggest Wednesdays so we aren't hustling to be on campus early
on Mondays. But this Wednesday I made coffee plans with a former Boulder
acquaintance. Can we start this next week and plan to do it weekly until we
deem it excessive?

**Comment by robfitzgerald** [comment]
^^
in other words, weekly starting wed 9/2 at 8:30 or 9:00 and occurring weekly until we decide otherwise?

**Comment by Wmaxlees** [comment]
Why so early?

**Comment by robfitzgerald** [comment]
Early?

**Comment by Wmaxlees** [comment]
Yeah. Why not meet after class. We're all free at 12:30 as well

**Comment by robfitzgerald** [comment]
Duh. Sorry I just realized I didn't know what you were talking about because I was looking at the thread in gmail and it only shows your posts not mine.
Sure that sounds great. Didn't know Jason's schedule.
