### ISSUE TITLE
thanks for coming email

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#29]
SWAG:
- thanks to those who came out tonight and congrats to the winning team whose name will go unmentioned here.  showing up at our regular events helps us for when we talk companies into getting involved, we can say we have a steady membership at ACM of UCD.
- any feedback on this event?
- welcome to new members
- to those who couldn't make it, please let us know if you have any ideas for events this and next semester, or any contacts who may want to plan an event with us

**Comment by robfitzgerald** [comment]
probs send something like this out tonight?  tomorrow maybs.

**Comment by Wmaxlees** [comment]
Did you send this off by any chance? I think it's fine

**Comment by robfitzgerald** [comment]
Not yet. Wanted feedback, thanks for giving it a read. Happy Friday

**Comment by Wmaxlees** [comment]
So it's getting pretty late to send this out. Did we miss the window?

**Comment by robfitzgerald** [comment]
Never too late. But ya let's do it today. I'm going to be at work until 7.
If you can do it sooner then be my guest. I'll set a reminder for 8 to send
it and I will if you haven't yet.

**Comment by robfitzgerald** [comment]
done-zo.
