### ISSUE TITLE
Alison Joucovsky - Home Sharing Program for Seniors

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#30]
Hi ACM Crew,

Please see the email below about a possible project. If you are interested you can contact her directly.

Thanks,

Sarah

From: Alison Joucovsky [mailto:ajoucovsky@jewishfamilyservice.org] 
Sent: Thursday, August 20, 2015 7:31 AM
To: CEAS, Computer Science ComputerScience@ucdenver.edu
Subject: Student Project Help

I am starting a nonprofit that will need some computer help. I am creating a program that will require the use of a matching tool. The concept is called Home Sharing and it is matching seniors needs, location, personality, living environment with someone who needs and affordable place to live. Basically trading space for help.

I would LOVE to have help in developing a program that would allow us to speed up the process using a computerized tool. Amazingly enough, all the programs I have spoken to around the country are all pen and paper.

My cell phone is 303 915 8264. If you could please put me in contact with the right person to help, I would really appreciate it.

Thanks-Alison Joucovsky

Alison Joucovsky, MALPC
JFS Colorado Senior Connections Program Coordinator
Jewish Family Service of Colorado
3201 S. Tamarac Drive
Denver, CO  80231-4394
Direct: 720.248.4591
Fax: 303.597.7700
www.jewishfamilyservice.org

**Comment by robfitzgerald** [comment]
SWAG at questions we want to know:
Date she hopes to have the program
Who uses the program
How many users
How do they access the program (web-based?)
Description of Tool (and then research to confirm it doesn't exist)
Confidentiality researched?

**Comment by minor-jason** [comment]
This project was accepted by senior design.
