### ISSUE TITLE
Find Space for Panel Event

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#38]
Find a room/location for the panel event for end of October

**Comment by Madylil95** [comment]
Found ACAD 1500 with capacity of 50. It's a classroom. Will confirm date and time and get badge access.

**Comment by Madylil95** [comment]
Hey guys! So all rooms in the Academic Building won't be free until 6:15 pm will that be okay? There are classes up until then. The only other room that I can book that is free at 6:00 pm and a little before that for prep is room 1100 in the CU building that fits 50 capacity as well, but isn't that nice. What do you think?

**Comment by robfitzgerald** [comment]
Does the class let out at 615? We probably want to then set doors at 630 then, at the earliest. I think that is workable, I think we should book it.

**Comment by Wmaxlees** [comment]
I agree with Rob
