### ISSUE TITLE
Panel event flyer

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#40]
Create and distribute a flyer for the panel event

**Comment by robfitzgerald** [comment]
James Jamison - Director, Technical Marketing - Cisco Systems
Doug Williams - Chief Research Scientist - SAIC
Shawn McCarthy - Director Cloud Computing - Vantiv
Eric Ray - Director, Platform Development - Nexenta
David Duncan - Vice President, Product Development - Alteryx

**Comment by Madylil95** [comment]
![cs panel_f](https://cloud.githubusercontent.com/assets/3596057/10501640/d23e2d68-72a0-11e5-83f1-b1ad79bbc4e3.jpg)
![cs panel_h](https://cloud.githubusercontent.com/assets/3596057/10501641/d23ee848-72a0-11e5-9a42-47f200188c4d.jpg)
![cs panel_v](https://cloud.githubusercontent.com/assets/3596057/10501639/d23df096-72a0-11e5-812e-11ffe43fbfcb.jpg)

**Comment by Madylil95** [comment]
![cs panel_v](https://cloud.githubusercontent.com/assets/3596057/10501696/42c9e55e-72a1-11e5-8a79-e4bcd6cfdc5f.jpg)
![cs panel_h](https://cloud.githubusercontent.com/assets/3596057/10501695/42c8f4d2-72a1-11e5-97c6-e3f5d853feb8.jpg)
![cs panel_f](https://cloud.githubusercontent.com/assets/3596057/10501694/42c56038-72a1-11e5-9173-bfc949d15503.jpg)

**Comment by Madylil95** [comment]
Questions, Comments, Concerns? Suggestions? 
F=Flyer, H=Horizontal Monitors, V=Vertical Monitors

**Comment by robfitzgerald** [comment]
Those look really great. I have no feedback about the design, I think it
has an attention-getting look.

Just checking one detail, the doors time. I know I want more time but Max
suggested doors at 620pm which I think everyone agreed on, right? If so,
let's list that for the time on the poster.

**Comment by robfitzgerald** [comment]
Of the two names styles, I would go with the one with name on left, company
on right, versus on multiple lines.

**Comment by robfitzgerald** [comment]
Did you make the light bulb tree?

**Comment by Madylil95** [comment]
Yeah. It started out as just mother board wires, but then I added bulbs, and then I guess it looked like a tree :) I didn't notice lol 
The two naming styles are due to the different sizes. The ones for the TV monitors fit in a single line. The one for the paper flyer though could not. I wanted their names to pop out so I made it real big.

**Comment by Madylil95** [comment]
I'll fix the time!

**Comment by robfitzgerald** [comment]
Oh OK didn't catch that. Well then, looks great to me, though I'd like to
hear from you or either Jason/Max about the time. I'll ask on Slack.

**Comment by Wmaxlees** [comment]
Those look really good. I think we're still waiting to find out about the table situation before we can decide when doors open, aren't we?

**Comment by robfitzgerald** [comment]
Re: table. I'll walk by there today and see if there is something we can use. I'll update here around 4pm.

**Comment by Madylil95** [comment]
![cs panel_f](https://cloud.githubusercontent.com/assets/3596057/10588578/2ce3ec0a-7664-11e5-9f63-c10935df5dc3.jpg)
![cs panel_h](https://cloud.githubusercontent.com/assets/3596057/10588576/2cde4318-7664-11e5-913f-510f17986a46.jpg)
![cs panel_v](https://cloud.githubusercontent.com/assets/3596057/10588577/2cde655a-7664-11e5-9cc2-0bacfdce595a.jpg)

**Comment by Madylil95** [comment]
Any typos? If not, to the printer!

**Comment by Madylil95** [comment]
![cs panel_f](https://cloud.githubusercontent.com/assets/3596057/10588903/bbc74f88-7665-11e5-80f6-2a1a6d5fea35.jpg)
![cs panel_h](https://cloud.githubusercontent.com/assets/3596057/10588904/bbc8775a-7665-11e5-9ed1-b2c7d72dedfd.jpg)
![cs panel_v](https://cloud.githubusercontent.com/assets/3596057/10588905/bbc93898-7665-11e5-8e4f-5a234026fe8a.jpg)
