### ISSUE TITLE
OrgSync panel announcement

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#41]
Create and send an announcement out on orgsync for the panel event

**Comment by robfitzgerald** [comment]
here's a stab at the details:

save the date
ACM Presents: CS Career Panel
Tuesday, November 3rd, 2015, 6:00pm
6:00pm doors, refreshments
6:30pm panel
location and panelists coming soon
come learn about the variety of careers possible in CS.  our panelists are from a variety of backgrounds and come with years of perspective.

**Comment by minor-jason** [comment]
Org->Synced

**Comment by minor-jason** [comment]
Save the date sent. More information will be disseminated as the event date approaches

**Comment by robfitzgerald** [comment]
I liked Org->Synced
