### ISSUE TITLE
Panel questions

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#42]
Create a list of questions to direct discussion at the panel event

**Comment by Wmaxlees** [comment]
People Presenting:

David Duncan
Eric Ray
James Jamison
Shawn McCarthy
Doug Williams

**Comment by robfitzgerald** [comment]
how about we put out an orgsync email to ask members about what questions they want to ask the panelists?  we can cherry pick if we get too many responses.

if you like the idea, let me know if you want me write/send it.
