### ISSUE TITLE
Prioritize Company Cold Call List

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#48]
Go through cold call list and prioritize list based on some clear criteria

**Comment by robfitzgerald** [comment]
added our no reply contacts. started going through and visiting the sites. trying to write generally how big they are (national? local?) and how active they seem (job listings, blog activity). so far they all look great, but that's just 5 in.

**Comment by robfitzgerald** [comment]
https://docs.google.com/spreadsheets/d/1cLyLatrLwPwXoSJ8LOkCk9vyLLjI7aCfYfS4aYXXshc/edit

**Comment by Wmaxlees** [comment]
Cool. I like the color coding. What did the bold mean again? We've already talked to them in the past about TechExpo?

**Comment by robfitzgerald** [comment]
Past tech expo attendees
