### ISSUE TITLE
Write Cold Call 'Script'

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#49]
Write an agenda for the cold call information to be shared.

**Comment by Wmaxlees** [comment]
[Google Doc](https://docs.google.com/document/d/1Miw2CuaS2Tf0Qlf2RtgBAQKgnIyhOA62l-QNhDEaj3o/edit?usp=sharing)

For anyone that wants to take a look and add details.

**Comment by robfitzgerald** [comment]
i kinda 'went hammer' on that google doc.  all of your stuff is in there still though.  i added a section before for just a short and sweet initial contact.

**Comment by Wmaxlees** [comment]
You did go ham on this. And you did it all as ucd.acm... Otherwise it all looks really good. One thing we should consider is the amount of time we were intending to put into this (I think we landed on about an hour a week), doing research and all that jazz may put us over the limit, possibly. At least if we're trying to do one company a week.

**Comment by robfitzgerald** [comment]
I did contact margho at sendgrid yesterday. Email. I'll go in person if I
don't hear back from her. I would say I'd go by tomorrow but I'm not sure I
can get over there on a Friday.
I was roped into an open house at readytalk yesterday by Greg. I'm going to
send an email over there. Jason was it you who were saying that David C
thinks this is a bad time to connect with them though?
