### ISSUE TITLE
New Member Pitch

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#5]
Create a pitch to make in front of class for new members

**Comment by robfitzgerald** [comment]
i guess we want to kinda wrap our heads around this one by mondayish, and it's due wednesday at the super-latest?  even better, it might want to be converted into a "pick classes to pitch ACM to and ask Sarah to get us in contact with the professor"?  maybe followed by a different story for each class, assigned to the broog who can stop by the class?

i'm gonna look at the CSCI fall class schedule real quick

**Comment by Wmaxlees** [comment]
I'm happy to do some pitches on Monday after Automata. I'm not sure when else I would be free to do them. I've been sort of winging them (as you saw) but it would be nice to have some bullet points so maybe we should just work those out. I probably won't memorize a speech anyway.

**Comment by robfitzgerald** [comment]
me neither.  i think winging it is fine for the informal introduction ice breaking nature of these quick presentations.  humor ++.  maybe not for boris though, i don't think he's gonna come to trivia night.

**Comment by robfitzgerald** [comment]
i could do some also on tuesday after algorithms (330) if there's a good class for that.

**Comment by robfitzgerald** [comment]
https://drive.google.com/file/d/0BxY5K8uxLychMk03eTk2bzB5aFE/view?usp=sharing

**Comment by robfitzgerald** [comment]
that's the fa2015 CSCI schedule

**Comment by Wmaxlees** [comment]
So for the 12:30 block we could split up and hit Doug's and Bert's classes which covers our bases there. But there are 4 classes in the next time slot

**Comment by robfitzgerald** [comment]
@Wmaxlees, from the schedule:

MW 12:30p
CSC 3412 Algorithms, Doug Williams 
CSCI 5012- Data Systems, Bert Hinrichs

MW 2:00p
CSC 2525 Assembly Language and Comp. Org, Diane Yoha (PC Lab) 
CSCI 3320 Advanced Programming, Aarti Munjal 
CSCI 5800/7800 Advanced Mobile and Ubiquitous System Tam Vu 
CSCI 3920 Java Applications, Bert Hinrichs

i'm thinking i'll hit the tuesday 3:30pm 1410 class.

**Comment by Wmaxlees** [comment]
I guess we could just email those professors and see if we can come in. Even if it's not at the beginning of class time. Then we could both go and hit all of them. That would be ideal for us but I don't know how the professors will feel about that.

**Comment by robfitzgerald** [comment]
i think that might be overkill?  but, i was going to email sarah for starters, to see about either getting their contacts and/or asking for us.

**Comment by Wmaxlees** [comment]
I don't know. We probably don't need to do it every event we have. But one time at the beginning of the school year/semester to say, "Hey, we exist. Come check us out" probably wouldn't be too bad, right?

**Comment by robfitzgerald** [comment]
ya not too bad, and i get that this would be just as an intro and not every event.
i'm trying to defend my study time - MW afternoon is my main block i've got planned for study.  but, it's so early in the semester and my weekend is pretty dead so i'll probably be fine.  i'll ask sarah about those classes.

**Comment by robfitzgerald** [comment]
actually, one more hesitation: it might be kinda weird/bad form to interrupt classes midway with our announcement.

**Comment by Wmaxlees** [comment]
I don't mind doing it alone either if it turns out you do wanna use that time for studjin. But we'll see what Sarah says

**Comment by Wmaxlees** [comment]
Right, that's why I want to ask the professors.

**Comment by robfitzgerald** [comment]
skip the 5000 level classes so we don't burn people out that we have talked with twice?

**Comment by robfitzgerald** [comment]
Mon 12:30pm Doug Algorithms
Mon 2:00pm Diane Assembly
Mon 2:30pm Aarti Advanced
Mon 3:00pm Bert Java
?

**Comment by Wmaxlees** [comment]
Assembly is only on wednesdays

**Comment by Wmaxlees** [comment]
Maybe I just do Doug for the group that's a year behind us and Bert for a wide range of undergrads. Skip Aarti's class

**Comment by robfitzgerald** [comment]
assembly is purple.  but, is it really just Wednesdays?  doesn't say.

**Comment by Wmaxlees** [comment]
Oh, you're right. That may be mondays. I was thinking the other purple one

**Comment by robfitzgerald** [comment]
sounds good.  you could even see about Doug @ 1:30p (end of his class) and Bert @ 2:00p (beginning of his)

**Comment by Wmaxlees** [comment]
ˁ(OᴥO)ˀ

**Comment by robfitzgerald** [comment]
```
                   .     _///_,
                 .      / ` ' '>
                   )   o'  __/_'>
                  (   /  _/  )_\'>
                   ' "__/   /_/\_>
                       ____/_/_/_/
                      /,---, _/ /
                     ""  /_/_/_/
                        /_(_(_(_                 \
                       (   \_\_\\_               )\
                        \'__\_\_\_\__            ).\
                        //____|___\__)           )_/
                        |  _  \'___'_(           /'
                         \_ (-'\'___'_\      __,'_'
                         __) \  \\___(_   __/.__,'
               b'ger  ,((,-,__\  '", __\_/. __,'
                                   '"./_._._-'
```

**Comment by robfitzgerald** [comment]
k i'll add tue 3:30 1410 to my list and i'll get in touch w/ sarah for the contact.  if you can wrangle me into it, i'll join you on monday for some dragon slaying.

**Comment by robfitzgerald** [comment]
oh wait, i'll try and go tomorrow instead :-P
