### ISSUE TITLE
Update orgsync

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#6]
OrgSync requires new information for this coming semester.

**Comment by robfitzgerald** [comment]
oh, wait, is this re: the renewal processing for Student Life?

**Comment by Wmaxlees** [comment]
No. This was specifically for OrgSync. I think you already did this, though, right?

**Comment by robfitzgerald** [comment]
well they are tied together.  Student Life makes you confirm you are still a student group / re-register July 1st, and they make you do it by logging in to OrgSync and completing a re-registration there.  I did do that, and that's all I did re: OrgSync or Student Life.
