### ISSUE TITLE
TBP wants a website

### ISSUE THREAD

**Issue by minor-jason** [acm-ucdenver/events#62]
for an event and would like ACM help. This could be done easily with a free Weebly site, etc.

**Comment by robfitzgerald** [comment]
Tao Beta Phi?
Ya we could do a weebly but maybe we could do a group project in angular too. Depending on the details. When do they want it, and what does the site do?

**Comment by minor-jason** [comment]
I forwarded the email.

**Comment by robfitzgerald** [comment]
Ok

**Comment by minor-jason** [comment]
I heard nothing from our members.
