### ISSUE TITLE
Background info on Eric Ray

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#66]
Get background information on Eric Ray from (Nexenta).

**Comment by minor-jason** [comment]
Get info from LinkedIn, copy to doc

**Comment by Wmaxlees** [comment]
Not sure where everyone is putting their biographies but:

Eric Ray is currently part of the advisory board for UC Denver. He is also on the Engineering Leadership Council for the college of engineering and applied science for UC Denver. He got a BA in German, Education, and History from Washington University in St. Louis and an MA in Technical Communication and English from Oklahoma State University. He has worked at Sun, Oracle, Citrus, and is currently working at Nexenta as Director of Platform Development.
