### ISSUE TITLE
SendGrid FieldTrip - OrgSyncAnnounceMent

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#68]
November 13th at 8:30AM. 
we're planning on having a handful of team members speak with the group. This will include several engineers and an infosec team member.
meet at lawrence 8:00am.

Contacting them to see about moving it later, since we are no longer attending a stand-up.

**Comment by Wmaxlees** [comment]
Send this out a bit after the Panel event orgsync announcement.

**Comment by robfitzgerald** [comment]
perhaps replaced by the rsvp i just sent out?
