### ISSUE TITLE
SendGrid - Flyer

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#69]
create flyer for sendgrid event, completed by October 26th.

i'm renegotiating the time. the rest of the details:

ACM SendGrid Visit
Friday, November 13th
[time]

SendGrid is an Email delivery and transaction service based in Colorado and California.  They deliver a high-performance email management service and a first class web API.  Their Denver office is located in Larimer Square, a few blocks from the Lawrence Street building.

Join us Friday morning for a visit to SendGrid, to meet software engineers and information security engineers, to have a discussion about the work they do.  Refreshments will be provided.

find out more about SendGrid at www.sendgrid.com

for information on ACM, please contact the ACM Chair: robert.fitzgerald@ucdenver.edu

**Comment by robfitzgerald** [comment]
time: 9:30a - 11:30a.  meet at Lawrence Street between 9:00 and 9:15.

**Comment by robfitzgerald** [comment]
Lily, can we have this flyer completed by our November 3rd Panel event, so flyers can be distributed at the Panel?
I think it would be useful to have a 4-up or 9-up handbill along with the usual A4 poster.  If you don't have time for both, we should probably stick to the A4.
Sound ok?

**Comment by Madylil95** [comment]
![sendgrid trip_b](https://cloud.githubusercontent.com/assets/3596057/10912881/9c7ad114-8208-11e5-9a79-ee37ef80bf92.jpg)
Sorry this is so late! If you would just review it real quick we can send it off to the printer right away!

**Comment by Wmaxlees** [comment]
Looks good. You have a '.!' on the second to last line. I would remove the ! since we have another one right after it. Otherwise, I think everything is good.

**Comment by Madylil95** [comment]
![sendgrid trip_b](https://cloud.githubusercontent.com/assets/3596057/10913105/c3acc368-8209-11e5-8c1b-1622af53cd3d.jpg)

**Comment by Madylil95** [comment]
Fixed!

**Comment by Madylil95** [comment]
Just sent to Sarah for print out
