### ISSUE TITLE
Create rough draft email for Tech Expo

### ISSUE THREAD

**Issue by Wmaxlees** [acm-ucdenver/events#72]
Create rough draft email to get people involved for tech expo and send it to Eric Ray to look over.

**Comment by Wmaxlees** [comment]
https://docs.google.com/document/d/1PRy39ISQrAOjlOrz_1fUyEQSnsblAw1bXnC3CLXkJmA/edit?usp=sharing

**Comment by robfitzgerald** [comment]
added a buncha little suggestions to letter 1.  rewrote the 2nd ¶ in letter 2.  thanks for busting this letter out.  happy travels, max!
