### ISSUE TITLE
Panelists thank you email

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#75]
write a thank you email to the panelists for participating.  tell them we can send them photos if they want.  maybe slip in a little thingie about the tech expo.

**Comment by robfitzgerald** [comment]
https://docs.google.com/document/d/1wrCdizetbm0WNm-jAbRKzbIcX3HAXv6pk7ciZ0ySobo/edit?usp=sharing

**Comment by robfitzgerald** [comment]
feel free to make suggestions on the doc above!

**Comment by Wmaxlees** [comment]
I went kinda ham on the letter. I tried to make comments about what I changed, though, so you can see my reasoning.

**Comment by robfitzgerald** [comment]
Sounds good. I wrote it tired in 5 minutes.

**Comment by Madylil95** [comment]
Looks great!

**Comment by minor-jason** [comment]
I like it
