### ISSUE TITLE
Create template emails

### ISSUE THREAD

**Issue by robfitzgerald** [acm-ucdenver/events#9]
- "we can't do your event" response due to general availability 
- "unable to do your suggested event" response due to unprecedented event requirements
- "your event is accepted and here's your new contact for the details" notification for handing off from intake to a specific operational lead
- "heads up, our deadline for booking your event is approaching" notification for when we are approaching our lead time cutoff of 4 weeks (2 weeks to make a flyer, 2 weeks of having the flyer out there)
- "deadline passed, apology letter to cancel event booking" notification when company drops the ball and misses our deadline, and we decide not to make a special case of it.

**Comment by Wmaxlees** [comment]
I'm going to split this up so we don't accidentally miss one.
